[forest]
parameters = [
    {weight=0.5, value=0.5},
    {weight=0.5, value=0.3},
    {weight=0.55, value=0.5}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {height=7, block="base:dirt"},
    {height=3, block="newgen:red_clay"},
    {height=-1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.42
plants = [
    {weight=1, block="base:grass"},
    {weight=0.05, block="newgen:dead_grass"},
    {weight=0.03, block="newgen:dead_tall_grass"},
    {weight=0.03, block="newgen:bush"},
    {weight=0.03, block="newgen:small_stick"},
    {weight=0.02, block="newgen:lily"},
    {weight=0.01, block="newgen:dead_bush"},
    {weight=0.01, block="newgen:blackberry_bush"},
    {weight=0.01, block="newgen:moss"},
    {weight=0.01, block="newgen:white_mushrooms"},
    {weight=0.01, block="newgen:chanterelles"}
]
structure-chance = 0.032
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1},
    {name="tree2", weight=1},
    {name="bush0", weight=0.5},
    {name="bush1", weight=0.5},
    {name="fallen_tree", weight=0.03},
    {name="fallen_mossy_tree", weight=0.03},
    {name="dead_tree", weight=0.02},
    {name="ruins0", weight=0.01},
    {name="camp", weight=0.01}
]


[spruce_forest]
parameters = [
    {weight=0.9, value=0.1},
    {weight=0.6, value=0.8},
    {weight=0.3, value=0.4}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {height=7, block="base:dirt"},
    {height=3, block="newgen:red_clay"},
    {height=-1, block="newgen:gabbro"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.5
plants = [
    {weight=1, block="base:grass"},
    {weight=0.05, block="newgen:dead_grass"},
    {weight=0.03, block="newgen:dead_tall_grass"},
    {weight=0.03, block="newgen:bush"},
    {weight=0.03, block="newgen:small_stick"},
    {weight=0.03, block="newgen:gabbro_stone"},
    {weight=0.02, block="newgen:lily"},
    {weight=0.03, block="newgen:clover"},
    {weight=0.01, block="newgen:dead_bush"},
    {weight=0.01, block="newgen:blackberry_bush"},
    {weight=0.01, block="newgen:cowberry_bush"},
    {weight=0.01, block="newgen:moss"},
    {weight=0.01, block="newgen:white_mushrooms"},
    {weight=0.01, block="newgen:chanterelles"}
]
structure-chance = 0.01
structures = [
    {name="spruce0", weight=1},
    {name="spruce1", weight=1},
    {name="bush0", weight=0.5},
    {name="bush1", weight=0.5},
    {name="gabbro_little_rock", weight=0.1},
    {name="fallen_spruce_tree", weight=0.03},
    {name="fallen_mossy_spruce_tree", weight=0.03},
    {name="dead_spruce_tree", weight=0.02},
    {name="gabbro_big_rock", weight=0.02},
    {name="ruins0", weight=0.01},
    {name="camp", weight=0.01}
]


[taiga]
parameters = [
    {weight=0.8, value=-0.5},
    {weight=0.6, value=0.3},
    {weight=0.3, value=0.4}
]
layers = [
    {below-sea-level=false, height=1, block="newgen:snow"},
    {height=7, block="base:dirt"},
    {height=3, block="newgen:red_clay"},
    {height=-1, block="newgen:gabbro"}
]
sea-layers = [
    {height=1, block="base:ice"},
    {height=-1, block="base:water"}
]
plant-chance = 0.65
plants = [
    {weight=1, block="newgen:snow_pile"},
    {weight=0.05, block="newgen:dead_white_bush"},
    {weight=0.05, block="newgen:dead_grass"},
    {weight=0.03, block="newgen:dead_tall_grass"}
]
structure-chance = 0.01
structures = [
    {name="spruce_snow0", weight=1},
    {name="spruce_snow1", weight=1},
    {name="dead_spruce_tree_snow", weight=0.02}
]

[desert]
parameters = [
    {weight=1, value=1},
    {weight=0.5, value=-1},
    {weight=0.45, value=0.6}
]
layers = [
    {height=6, block="base:sand"},
    {height=20, block="newgen:sandstone"},
    {height=25, block="newgen:gneiss"},
    {height=-1, block="newgen:granite"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.1
plants = [
    {weight=0.5, block="newgen:sandstone_stone"},
    {weight=0.05, block="newgen:dead_grass"},
    {weight=0.03, block="newgen:dead_tall_grass"},
    {weight=0.03, block="newgen:dead_bush"},
    {weight=0.01, block="newgen:coal_stone"}
]
structure-chance=0.01
structures = [
    {name="sandstone_coal0", weight=0.1},
    {name="sandstone_coal1", weight=1}
]

[mountains]
parameters = [
    {weight=1, value=0.4},
    {weight=1, value=0.9},
    {weight=1, value=1}
]
layers = [
    {height=20, block="newgen:limestone"},
    {height=-1, block="newgen:marble"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.25
plants = [
    {weight=0.7, block="base:grass"},
    {weight=0.05, block="newgen:dead_grass"},
    {weight=0.04, block="newgen:marble_stone"},
    {weight=0.03, block="newgen:dead_tall_grass"},
    {weight=0.03, block="newgen:dead_bush"},
    {weight=0.03, block="newgen:bush"},
    {weight=0.01, block="newgen:malachite_stone"},
    {weight=0.01, block="newgen:coal_stone"}
]
structure-chance=0.01
structures = [
    {name="limestone_coal0", weight=0.1},
    {name="limestone_coal1", weight=1},
    {name="limestone_malachite_ore", weight=0.3},
    {name="marble_little_rock", weight=0.1},
    {name="marble_big_rock", weight=0.02}
]


[plains]
parameters = [
    {weight=0.6, value=0.5},
    {weight=0.6, value=0.5},
    {weight=0.5, value=0.3}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {height=6, block="base:dirt"},
    {height=5, block="newgen:red_clay"},
    {height=-1, block="newgen:diorite"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.45
plants = [
    {weight=1, block="base:grass"},
    {weight=0.05, block="newgen:dead_grass"},
    {weight=0.03, block="newgen:dead_tall_grass"},
    {weight=0.03, block="newgen:dead_bush"},
    {weight=0.03, block="newgen:bush"},
    {weight=0.02, block="newgen:dandelions"},
    {weight=0.03, block="newgen:clover"},
    {weight=0.02, block="newgen:daisies"},
    {weight=0.02, block="newgen:knapweeds"},
    {weight=0.01, block="newgen:flax"},
    {weight=0.01, block="newgen:calendula"}
]
structure-chance=0.005
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1},
    {name="bush0", weight=5},
    {name="bush1", weight=5},
    {name="diorite_little_rock", weight=0.12},
    {name="diorite_big_rock", weight=0.03},
    {name="fallen_tree", weight=0.03},
    {name="fallen_mossy_tree", weight=0.03},
    {name="dead_tree", weight=0.02},
    {name="ruins0", weight=0.01},
    {name="camp", weight=0.01}
]

[swamp]
parameters = [
    {weight=0.9, value=0.5},
    {weight=1, value=1},
    {weight=0.3, value=0.2}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {height=30, block="base:dirt"},
    {height=7, block="newgen:red_clay"},
    {height=-1, block="newgen:dolomite"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.5
plants = [
    {weight=1, block="base:grass"},
    {weight=0.05, block="newgen:cattail"},
    {weight=0.05, block="newgen:bush"},
    {weight=0.03, block="newgen:dead_grass"},
    {weight=0.03, block="newgen:small_stick"},
    {weight=0.02, block="newgen:dead_tall_grass"},
    {weight=0.02, block="newgen:daisies"},
    {weight=0.01, block="newgen:dead_bush"},
    {weight=0.01, block="newgen:dolomite_stone"},
    {weight=0.01, block="newgen:malachite_stone"},
    {weight=0.01, block="newgen:coal_stone"}
]
structure-chance = 0.03
structures = [
    {name="dolomite_coal0", weight=0.05},
    {name="dolomite_coal1", weight=0.5},
    {name="dolomite_malachite_ore", weight=0.3},
    {name="spruce0", weight=1},
    {name="spruce1", weight=1},
    {name="bush0", weight=0.5},
    {name="bush1", weight=0.5},
    {name="puddle", weight=0.05},
    {name="fallen_mossy_spruce_tree", weight=0.03},
    {name="dead_spruce_tree", weight=0.02},
    {name="ruins0", weight=0.01}
]